"""add table planification_chaine_model

Revision ID: 4b17d42fcfd5
Revises: 723058177c97
Create Date: 2025-07-15 09:51:34.280891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b17d42fcfd5'
down_revision = '723058177c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateCreation', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('etat', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('inventaire', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('magasin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nbre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DF', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('observation', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('export', sa.String(length=20), nullable=True))
        batch_op.alter_column('numOF',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('Pointure',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('Modele',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('Coloris',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('SAIS',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('dateLancement',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('colisNonEmb',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'planification_chaine_modeles', ['idPlanification'], ['id'])

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ouvriers', ['matOuvrier'], ['MATR'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    with op.batch_alter_table('planification', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['chaine'], ['id'])

    with op.batch_alter_table('planification_chaine_modeles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['chaine'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planification_chaine_modeles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.alter_column('colisNonEmb',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('dateLancement',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('SAIS',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=False)
        batch_op.alter_column('Coloris',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
        batch_op.alter_column('Modele',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('Pointure',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
        batch_op.alter_column('numOF',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('export')
        batch_op.drop_column('observation')
        batch_op.drop_column('DF')
        batch_op.drop_column('nbre')
        batch_op.drop_column('magasin')
        batch_op.drop_column('inventaire')
        batch_op.drop_column('etat')
        batch_op.drop_column('dateCreation')

    # ### end Alembic commands ###
