"""ajout colonne authorized dans la table user

Revision ID: 4b24da7c7f4e
Revises: a8e211a95f8f
Create Date: 2025-06-19 09:22:26.501432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b24da7c7f4e'
down_revision = 'a8e211a95f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numCommande'])
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorized', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('authorized')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
