"""update table ofs_chaine ajout des colonnes regimeHoraire et idPlanifiction

Revision ID: 63f12dc570e2
Revises: d696e02a492e
Create Date: 2025-07-12 09:25:42.696520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f12dc570e2'
down_revision = 'd696e02a492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regimeHoraire', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('idPlanification', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'planification', ['idPlanification'], ['id'])

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ouvriers', ['matOuvrier'], ['MATR'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])

    with op.batch_alter_table('planification', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['chaine'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idPlanification')
        batch_op.drop_column('regimeHoraire')

    # ### end Alembic commands ###
