"""ajouter colonnes etat dateCreation

Revision ID: 750082734841
Revises: 7afe0d953065
Create Date: 2025-06-25 09:35:09.865862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750082734841'
down_revision = '7afe0d953065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateCreation', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('etat', sa.String(length=20), nullable=True))
        batch_op.alter_column('dateLancement',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ouvriers', ['matOuvrier'], ['MATR'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.alter_column('dateLancement',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('etat')
        batch_op.drop_column('dateCreation')

    # ### end Alembic commands ###
