"""changer nom tables

Revision ID: 7afe0d953065
Revises: e2808949a892
Create Date: 2025-06-23 13:22:38.559347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afe0d953065'
down_revision = 'e2808949a892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ouvriers', ['matOuvrier'], ['MATR'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
