"""Création du table users

Revision ID: a8e211a95f8f
Revises: a8fb785fd420
Create Date: 2025-06-13 16:22:26.720340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8e211a95f8f'
down_revision = 'a8fb785fd420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('decgrdp500')
    op.drop_table('decleather')
    op.drop_table('dec500')
    op.drop_table('decmmdw')
    op.drop_table('dec900')
    op.drop_table('decgas580')
    op.drop_table('dec500_dcdp500s')
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numCommande'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('dec500_dcdp500s',
    sa.Column('Réf_Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code_Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('decgas580',
    sa.Column('Réf.Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(precision=10, scale=4), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dec900',
    sa.Column('Réf.Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('decmmdw',
    sa.Column('Réf.Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(precision=10, scale=4), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dec500',
    sa.Column('Réf.Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(precision=10, scale=4), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('decleather',
    sa.Column('Réf.Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('decgrdp500',
    sa.Column('Réf.Article:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Coloris:', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Code Matière', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Libellé', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('Coloris', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('Unité', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('Qté', mysql.FLOAT(), nullable=True),
    sa.Column('PHASE', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
