"""Création des tables

Revision ID: a8fb785fd420
Revises: 
Create Date: 2025-06-13 14:34:36.258841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fb785fd420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofs',
    sa.Column('numCommande', sa.Integer(), nullable=False),
    sa.Column('dateLancement', sa.Date(), nullable=False),
    sa.Column('pointure', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('numCommande')
    )
    op.create_table('type_chaine',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofs_chaine',
    sa.Column('idChaine', sa.String(length=20), nullable=False),
    sa.Column('numCommandeOF', sa.Integer(), nullable=False),
    sa.Column('dateLancement_of_chaine', sa.Date(), nullable=True),
    sa.Column('dateFin', sa.Date(), nullable=True),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('MatOuvrier1', sa.Integer(), nullable=True),
    sa.Column('MatOuvrier2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idChaine'], ['type_chaine.id'], ),
    sa.ForeignKeyConstraint(['numCommandeOF'], ['ofs.numCommande'], ),
    sa.PrimaryKeyConstraint('idChaine', 'numCommandeOF')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofs_chaine')
    op.drop_table('users')
    op.drop_table('type_chaine')
    op.drop_table('ofs')
    # ### end Alembic commands ###
