"""update size of modele column

Revision ID: d696e02a492e
Revises: 6fbbd6847c8e
Create Date: 2025-07-11 12:28:40.266477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd696e02a492e'
down_revision = '6fbbd6847c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])
        batch_op.create_foreign_key(None, 'ouvriers', ['matOuvrier'], ['MATR'])

    with op.batch_alter_table('planification', schema=None) as batch_op:
        batch_op.alter_column('modele',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'type_chaine', ['chaine'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('modele',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
