"""ajouter table ouvrier et ouvrier_chaine_of et changement des noms de colonnes de la table of

Revision ID: e2808949a892
Revises: 214e413d7393
Create Date: 2025-06-23 11:52:03.112943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2808949a892'
down_revision = '214e413d7393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ouvriers',
    sa.Column('MATR', sa.Integer(), nullable=False),
    sa.Column('NOM', sa.String(length=20), nullable=False),
    sa.Column('PRENOM', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('MATR')
    )
    op.create_table('ouvrier_chaine_ofs',
    sa.Column('idChaine', sa.String(length=20), nullable=False),
    sa.Column('numCommandeOF', sa.Integer(), nullable=False),
    sa.Column('matOuvrier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idChaine'], ['type_chaine.id'], ),
    sa.ForeignKeyConstraint(['matOuvrier'], ['ouvriers.MATR'], ),
    sa.ForeignKeyConstraint(['numCommandeOF'], ['ofs.numOF'], ),
    sa.PrimaryKeyConstraint('idChaine', 'numCommandeOF', 'matOuvrier')
    )
    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numOF', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Modele', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('COL', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('SAIS', sa.String(length=20), nullable=False))
        batch_op.drop_column('numCommande')
        batch_op.drop_column('article')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.drop_column('MatOuvrier1')
        batch_op.drop_column('MatOuvrier2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MatOuvrier2', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MatOuvrier1', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('numCommande', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('SAIS')
        batch_op.drop_column('COL')
        batch_op.drop_column('Modele')
        batch_op.drop_column('numOF')

    op.drop_table('ouvrier_chaine_ofs')
    op.drop_table('ouvriers')
    # ### end Alembic commands ###
