"""ajouter colonnes obs,df,nbr,colis,inventaire dans OFS

Revision ID: e7a1b8e46248
Revises: 750082734841
Create Date: 2025-07-04 08:26:29.989216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a1b8e46248'
down_revision = '750082734841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventaire', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('magasin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nbre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('colisNonEmb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DF', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('observation', sa.String(length=20), nullable=True))

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])

    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'type_chaine', ['idChaine'], ['id'])
        batch_op.create_foreign_key(None, 'ouvriers', ['matOuvrier'], ['MATR'])
        batch_op.create_foreign_key(None, 'ofs', ['numCommandeOF'], ['numOF'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ouvrier_chaine_ofs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs_chaine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ofs', schema=None) as batch_op:
        batch_op.drop_column('observation')
        batch_op.drop_column('DF')
        batch_op.drop_column('colisNonEmb')
        batch_op.drop_column('nbre')
        batch_op.drop_column('magasin')
        batch_op.drop_column('inventaire')

    # ### end Alembic commands ###
